### ISSUE TITLE
As an AQ data analyst, I expect that all data with period = 3600 are available as open data

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#130] opened 2019-09-13 06:13 UTC
- add a flight rule on how the workflow to define access policies work
  - have a shared document with all the policies
- verify all policies on the document and in the rule engine which has NO WEB UI, because of decisions of PO in the past

**Comment by bertolla** [comment] 2019-09-17 12:21
@rcavaliere 
Can't find that document with the policies. Do you know where it is?

**Comment by rcavaliere** [comment] 2019-09-17 16:22
@bertolla Do you want that we update this one: https://docs.google.com/spreadsheets/d/16Bok6Vd_PsRRZF1E_WR-uk2Y2Q1nZIlpTfOuu5Rvl4c/edit#gid=0 ?

**Comment by bertolla** [comment] 2019-09-18 08:06
Didn't we have something else, because we have no detail information in there like the period 3600 period

**Comment by rcavaliere** [comment] 2019-09-18 08:08
Sincerly I don't remember, but I can update this information with all actual information

**Comment by bertolla** [comment] 2019-09-18 12:18
At this point it might be better to comment it in the already existing sql file where data gets imported:
https://github.com/noi-techpark/bdp-core/blob/master/dal/src/main/resources/META-INF/sql/opendatarules.sql

**Comment by rcavaliere** [comment] 2019-09-18 15:39
OK, I noticed that for air quality data there is a difference if one wants APPABZ data and data from other providers. The rule should be that data with period = 3600 from ALL providers are open for everyone. Do you want that we sit down 10 minutes together and update together the rules?

**Comment by bertolla** [comment] 2019-09-19 09:02
I will now make that work. Maybe it would be good if we use the comments to describe the rules better and use it as our ruledoc

**Comment by rcavaliere** [comment] 2019-09-19 09:12
Agree. Let's use this sql file as master for all the open / closed data rules

**Comment by bertolla** [comment] 2019-09-19 14:24
I noticed that even thought in the opendatarules the period is specified the API still did not work as expected and therefore opened this issue in bdp-core #noi-techpark/bdp-core/issues/110

**Comment by ohnewein** [comment] 2019-09-27 07:59
The issue is that https://ipchannels.integreen-life.bz.it/environment/rest/get-newest-record?station=APPATN_27 doesn't provide Open Data

**Comment by rcavaliere** [comment] 2019-09-27 09:34
@ohnewein  Please consider that this station is the only one of APPABZ and APPATN which does NOT provide hourly measurements. If you try e.g. https://ipchannels.integreen-life.bz.it/environment/rest/get-newest-record?station=APPATN-open_23 you get something. @bertolla now it seems to work fine, shall we close this issue? If you now navigate on analytics.mobility.bz.it (map) you can see what measurements are freely available

**Comment by rcavaliere** [comment] 2019-10-03 17:56
@bertolla I think we still some have some issues with the authentication side, now I don't get any air quality data with period = 3600...

**Comment by Piiit** [comment] 2019-10-14 12:23
@rcavaliere @ohnewein @bertolla 
This issue results from the way I thought of permissions which were a hierarchical tuple (station, data type, period). So, if you only set (station, NULL, period) the calculation did not consider that rule at all, because it is errornous as it was planned, e.g. not hierarchical anymore. Now also the new use case with (station, NULL, period) is supported at should already work on TEST and PRODUCTION.

@rcavaliere Could you please test.

**Comment by rcavaliere** [comment] 2019-10-19 05:21
@piit nice, but if I try to get data now without authentication I also get also data which should be closed...
![Screenshot from 2019-10-19 07-21-18](https://user-images.githubusercontent.com/9825179/67138279-1de73b00-f241-11e9-8f15-c57aebba2099.png)

**Comment by Piiit** [comment] 2019-10-21 07:45
@rcavaliere As already communicated, I was not able to reproduce the error. Maybe it was a caching, session error of the analytics webapp. The API does not leak non-open data. Closing for now. Please reopen if the error occurs again.

**Closed by Piiit** 2019-10-21 07:45 UTC
Labels: bug
