### ISSUE TITLE
As a meteo expert I would like to verify if the ODH is at present providing all the open data measurements provided by the Province of Bolzano

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#224] opened 2021-01-03 06:50 UTC
We probably have an issue with the ingestion of the open data measurements of the Province of Bolzano.

End-point used (for ingestion in the ODH):
http://dati.retecivica.bz.it/services/meteo/v1/stations
http://dati.retecivica.bz.it/services/meteo/v1/sensors

Data provided by the ODH:
https://analytics.opendatahub.bz.it/

It seems that are present we are currently getting only the data of the hydrometric stations, which measure the status of the water rivers.

**Comment by bertolla** [comment] 2021-01-07 11:59
Data collector stopped on 6/12. I restarted the collector and it's currently importing all historical data

**Comment by bertolla** [comment] 2021-01-07 14:49
I investigated further and I found out that v2 was just exposing data where the available flag was set and therefore you could not see any data of those stations. The `available` flag was just a flag in the past for bluetooth boxes. Why is it now used for all stations to decide if to show or not? I think this is wrong and the available flag is just there for legacy reasons. We probably can remove it. No every time a station is created and the flag is not set, the station will not be shown. Might be a big problem.

**Comment by rcavaliere** [comment] 2021-01-07 15:04
@bertolla I thought the logic was a little bit different, data should be available by default and eventually set as available = FALSE just for exceptions. Did you already changed this logic for the meteo data of the Province?

**Comment by bertolla** [comment] 2021-01-08 07:29
The problem is that mobility v2 is not showing stations where the flag is not set. Most datacollector **do not** set this flag and therefore they are not shown. Even if I set them the datacollector will unset them again on the next push.

**Comment by Piiit** [comment] 2021-01-13 19:23
@bertolla @rcavaliere Should I therefore revert what we have done for the available flag, or just consider NULL values as TRUE?

**Comment by rcavaliere** [comment] 2021-01-13 21:20
@Piiit with @bertolla we were considering the possibility to delete this coloumn, but probably this could have negative impacts somewhere... probably the best way would be to set the rule if NULL -> then consider as TRUE, so that we don't publish something only in the remote case we have explicitly set this flag to FALSE

**Comment by bertolla** [comment] 2021-01-18 08:00
@Piiit Can you change this in this sprint?

**Comment by Piiit** [comment] 2021-01-22 09:36
We decided to change it on the DB to just have TRUE or FALSE and then set a not null constraint

**Comment by Piiit** [comment] 2021-01-27 10:45
@bertolla @rcavaliere Done on testing with 

```sql
update station set available = true where available is null;
ALTER TABLE ONLY station ALTER COLUMN available SET DEFAULT true;
ALTER TABLE ONLY station ALTER COLUMN available SET NOT NULL;
```

Should we go for production now?

**Comment by rcavaliere** [comment] 2021-01-27 10:46
For me OK

**Comment by Piiit** [comment] 2021-01-27 10:55
Done, can we close it now?

**Closed** 2021-01-27 10:57 UTC
